seed: 42
device: cuda:0
num_steps_per_env: 24
max_iterations: 8000
empirical_normalization: false
policy:
  class_name: ActorCritic
  init_noise_std: 1.0
  noise_std_type: scalar
  actor_hidden_dims:
  - 128
  - 128
  - 128
  critic_hidden_dims:
  - 128
  - 128
  - 128
  activation: elu
algorithm:
  class_name: PPOSymmDataAugmented
  num_learning_epochs: 5
  num_mini_batches: 4
  learning_rate: 0.001
  schedule: fixed
  gamma: 0.99
  lam: 0.95
  entropy_coef: 0.005
  desired_kl: 0.01
  max_grad_norm: 1.0
  value_loss_coef: 1.0
  use_clipped_value_loss: true
  clip_param: 0.2
  normalize_advantage_per_mini_batch: false
  symmetry_cfg: null
  rnd_cfg: null
clip_actions: null
save_interval: 50
experiment_name: rough_direct
run_name: go2_imu_only
logger: wandb
neptune_project: basic-rl
wandb_project: basic-rl
resume: false
load_run: .*
load_checkpoint: model_.*.pt
amp_data_path: ./../../../amp_dataset/
dataset_names:
- flat
- boxes
- stairs
dataset_weights:
- 1.0
- 1.0
- 1.0
- 1.0
slow_down_factor: 1.0
discriminator:
  class_name: Discriminator
  hidden_dims:
  - 1024
  - 512
  reward_scale: 1.0
history_length: 5
obs_space_names_actor:
- base_lin_vel:base
- base_ang_vel:base
- gravity:base
- ctrl_commands
- default_qpos_js_error
- qvel_js
- actions
- clock_data
- base_lin_vel:base
- base_ang_vel:base
- gravity:base
- ctrl_commands
- default_qpos_js_error
- qvel_js
- actions
- clock_data
- base_lin_vel:base
- base_ang_vel:base
- gravity:base
- ctrl_commands
- default_qpos_js_error
- qvel_js
- actions
- clock_data
- base_lin_vel:base
- base_ang_vel:base
- gravity:base
- ctrl_commands
- default_qpos_js_error
- qvel_js
- actions
- clock_data
- base_lin_vel:base
- base_ang_vel:base
- gravity:base
- ctrl_commands
- default_qpos_js_error
- qvel_js
- actions
- clock_data
obs_space_names_critic:
- base_lin_vel:base
- base_ang_vel:base
- gravity:base
- ctrl_commands
- default_qpos_js_error
- qvel_js
- actions
- clock_data
- base_lin_vel:base
- base_ang_vel:base
- gravity:base
- ctrl_commands
- default_qpos_js_error
- qvel_js
- actions
- clock_data
- base_lin_vel:base
- base_ang_vel:base
- gravity:base
- ctrl_commands
- default_qpos_js_error
- qvel_js
- actions
- clock_data
- base_lin_vel:base
- base_ang_vel:base
- gravity:base
- ctrl_commands
- default_qpos_js_error
- qvel_js
- actions
- clock_data
- base_lin_vel:base
- base_ang_vel:base
- gravity:base
- ctrl_commands
- default_qpos_js_error
- qvel_js
- actions
- clock_data
morphologycal_symmetries_cfg:
  class_name: MorphologycalSymmetries
  obs_space_names_actor:
  - base_lin_vel:base
  - base_ang_vel:base
  - gravity:base
  - ctrl_commands
  - default_qpos_js_error
  - qvel_js
  - actions
  - clock_data
  - base_lin_vel:base
  - base_ang_vel:base
  - gravity:base
  - ctrl_commands
  - default_qpos_js_error
  - qvel_js
  - actions
  - clock_data
  - base_lin_vel:base
  - base_ang_vel:base
  - gravity:base
  - ctrl_commands
  - default_qpos_js_error
  - qvel_js
  - actions
  - clock_data
  - base_lin_vel:base
  - base_ang_vel:base
  - gravity:base
  - ctrl_commands
  - default_qpos_js_error
  - qvel_js
  - actions
  - clock_data
  - base_lin_vel:base
  - base_ang_vel:base
  - gravity:base
  - ctrl_commands
  - default_qpos_js_error
  - qvel_js
  - actions
  - clock_data
  obs_space_names_critic:
  - base_lin_vel:base
  - base_ang_vel:base
  - gravity:base
  - ctrl_commands
  - default_qpos_js_error
  - qvel_js
  - actions
  - clock_data
  - base_lin_vel:base
  - base_ang_vel:base
  - gravity:base
  - ctrl_commands
  - default_qpos_js_error
  - qvel_js
  - actions
  - clock_data
  - base_lin_vel:base
  - base_ang_vel:base
  - gravity:base
  - ctrl_commands
  - default_qpos_js_error
  - qvel_js
  - actions
  - clock_data
  - base_lin_vel:base
  - base_ang_vel:base
  - gravity:base
  - ctrl_commands
  - default_qpos_js_error
  - qvel_js
  - actions
  - clock_data
  - base_lin_vel:base
  - base_ang_vel:base
  - gravity:base
  - ctrl_commands
  - default_qpos_js_error
  - qvel_js
  - actions
  - clock_data
  action_space_names:
  - actions
  joints_order:
  - FL_hip_joint
  - FR_hip_joint
  - RL_hip_joint
  - RR_hip_joint
  - FL_thigh_joint
  - FR_thigh_joint
  - RL_thigh_joint
  - RR_thigh_joint
  - FL_calf_joint
  - FR_calf_joint
  - RL_calf_joint
  - RR_calf_joint
  robot_name: a1
