// Generated by gencpp from file dls_msgs/rl_signal_in.msg
// DO NOT EDIT!


#ifndef DLS_MSGS_MESSAGE_RL_SIGNAL_IN_H
#define DLS_MSGS_MESSAGE_RL_SIGNAL_IN_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace dls_msgs
{
template <class ContainerAllocator>
struct rl_signal_in_
{
  typedef rl_signal_in_<ContainerAllocator> Type;

  rl_signal_in_()
    : header()
    , position()
    , linear_velocity()
    , orientation_quat()
    , orientation_euler()
    , angular_velocity()
    , joint_positions()
    , joint_velocities()  {
      position.assign(0.0);

      linear_velocity.assign(0.0);

      orientation_quat.assign(0.0);

      orientation_euler.assign(0.0);

      angular_velocity.assign(0.0);

      joint_positions.assign(0.0);

      joint_velocities.assign(0.0);
  }
  rl_signal_in_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , position()
    , linear_velocity()
    , orientation_quat()
    , orientation_euler()
    , angular_velocity()
    , joint_positions()
    , joint_velocities()  {
  (void)_alloc;
      position.assign(0.0);

      linear_velocity.assign(0.0);

      orientation_quat.assign(0.0);

      orientation_euler.assign(0.0);

      angular_velocity.assign(0.0);

      joint_positions.assign(0.0);

      joint_velocities.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<double, 3>  _position_type;
  _position_type position;

   typedef boost::array<double, 3>  _linear_velocity_type;
  _linear_velocity_type linear_velocity;

   typedef boost::array<double, 4>  _orientation_quat_type;
  _orientation_quat_type orientation_quat;

   typedef boost::array<double, 3>  _orientation_euler_type;
  _orientation_euler_type orientation_euler;

   typedef boost::array<double, 3>  _angular_velocity_type;
  _angular_velocity_type angular_velocity;

   typedef boost::array<double, 12>  _joint_positions_type;
  _joint_positions_type joint_positions;

   typedef boost::array<double, 12>  _joint_velocities_type;
  _joint_velocities_type joint_velocities;





  typedef boost::shared_ptr< ::dls_msgs::rl_signal_in_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dls_msgs::rl_signal_in_<ContainerAllocator> const> ConstPtr;

}; // struct rl_signal_in_

typedef ::dls_msgs::rl_signal_in_<std::allocator<void> > rl_signal_in;

typedef boost::shared_ptr< ::dls_msgs::rl_signal_in > rl_signal_inPtr;
typedef boost::shared_ptr< ::dls_msgs::rl_signal_in const> rl_signal_inConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dls_msgs::rl_signal_in_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dls_msgs::rl_signal_in_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dls_msgs::rl_signal_in_<ContainerAllocator1> & lhs, const ::dls_msgs::rl_signal_in_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.position == rhs.position &&
    lhs.linear_velocity == rhs.linear_velocity &&
    lhs.orientation_quat == rhs.orientation_quat &&
    lhs.orientation_euler == rhs.orientation_euler &&
    lhs.angular_velocity == rhs.angular_velocity &&
    lhs.joint_positions == rhs.joint_positions &&
    lhs.joint_velocities == rhs.joint_velocities;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dls_msgs::rl_signal_in_<ContainerAllocator1> & lhs, const ::dls_msgs::rl_signal_in_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dls_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dls_msgs::rl_signal_in_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dls_msgs::rl_signal_in_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dls_msgs::rl_signal_in_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dls_msgs::rl_signal_in_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dls_msgs::rl_signal_in_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dls_msgs::rl_signal_in_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dls_msgs::rl_signal_in_<ContainerAllocator> >
{
  static const char* value()
  {
    return "78b51508ca7b56859062573cc269aae1";
  }

  static const char* value(const ::dls_msgs::rl_signal_in_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x78b51508ca7b5685ULL;
  static const uint64_t static_value2 = 0x9062573cc269aae1ULL;
};

template<class ContainerAllocator>
struct DataType< ::dls_msgs::rl_signal_in_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dls_msgs/rl_signal_in";
  }

  static const char* value(const ::dls_msgs::rl_signal_in_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dls_msgs::rl_signal_in_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header \n"
"\n"
"# system state\n"
"float64[3] position\n"
"float64[3] linear_velocity\n"
"float64[4] orientation_quat\n"
"float64[3] orientation_euler\n"
"float64[3] angular_velocity\n"
"float64[12] joint_positions\n"
"float64[12] joint_velocities\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::dls_msgs::rl_signal_in_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dls_msgs::rl_signal_in_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.position);
      stream.next(m.linear_velocity);
      stream.next(m.orientation_quat);
      stream.next(m.orientation_euler);
      stream.next(m.angular_velocity);
      stream.next(m.joint_positions);
      stream.next(m.joint_velocities);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rl_signal_in_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dls_msgs::rl_signal_in_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dls_msgs::rl_signal_in_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.position[i]);
    }
    s << indent << "linear_velocity[]" << std::endl;
    for (size_t i = 0; i < v.linear_velocity.size(); ++i)
    {
      s << indent << "  linear_velocity[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.linear_velocity[i]);
    }
    s << indent << "orientation_quat[]" << std::endl;
    for (size_t i = 0; i < v.orientation_quat.size(); ++i)
    {
      s << indent << "  orientation_quat[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.orientation_quat[i]);
    }
    s << indent << "orientation_euler[]" << std::endl;
    for (size_t i = 0; i < v.orientation_euler.size(); ++i)
    {
      s << indent << "  orientation_euler[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.orientation_euler[i]);
    }
    s << indent << "angular_velocity[]" << std::endl;
    for (size_t i = 0; i < v.angular_velocity.size(); ++i)
    {
      s << indent << "  angular_velocity[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.angular_velocity[i]);
    }
    s << indent << "joint_positions[]" << std::endl;
    for (size_t i = 0; i < v.joint_positions.size(); ++i)
    {
      s << indent << "  joint_positions[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint_positions[i]);
    }
    s << indent << "joint_velocities[]" << std::endl;
    for (size_t i = 0; i < v.joint_velocities.size(); ++i)
    {
      s << indent << "  joint_velocities[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint_velocities[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DLS_MSGS_MESSAGE_RL_SIGNAL_IN_H
